package com.coen6313g2.demo.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName="userdata")
public class UserModel implements Serializable {
	
	private String userid;
	private String cognitoId;
	private String email;
	
		private String firstName;
		private String lastName;
		private String mobileNumber;
		private String address;
		private String gender;
		private String typeOfUser;
		private String profileStatus;
		
		private String imagebase64;

	@DynamoDBHashKey(attributeName="userid")
	@DynamoDBAutoGeneratedKey
	public String getUserId() {
		return userid;
	}
	public void setUserId(String userid) {
		this.userid = userid;
	}
	
	
	@DynamoDBAttribute
	public String getCognitoId() {
		return cognitoId;
	}
	public void setCognitoId(String cognitoId) {
		this.cognitoId = cognitoId;
	}
	@DynamoDBAttribute
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	@DynamoDBAttribute
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	
	
	@DynamoDBAttribute
	public String getImagebase64() {
		return imagebase64;
	}
	public void setImagebase64(String imagebase64) {
		this.imagebase64 = imagebase64;
	}
	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	@DynamoDBAttribute
	public String getMobileNumber() {
		return mobileNumber;
	}
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	
	@DynamoDBAttribute
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	
	@DynamoDBAttribute
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	@DynamoDBAttribute
	public String getTypeOfUser() {
		return typeOfUser;
	}
	public void setTypeOfUser(String typeOfUser) {
		this.typeOfUser = typeOfUser;
	}
	
	@DynamoDBAttribute
	public String getProfileStatus() {
		return profileStatus;
	}
	public void setProfileStatus(String profileStatus) {
		this.profileStatus = profileStatus;
	}
	@Override
	public String toString() {
		return "UserModel [userid=" + userid + ", cognitoId=" + cognitoId + ", email=" + email + ", firstName="
				+ firstName + ", lastName=" + lastName + ", mobileNumber=" + mobileNumber + ", address=" + address
				+ ", gender=" + gender + ", typeOfUser=" + typeOfUser + ", profileStatus=" + profileStatus + "]";
	}
	
	
	
	

}
