let tabledata = [
  {
    fileNo: "1245",
    tradeMarkId: 454333,
    name: "diset",
    applicationDate: "21-05-2020",
    applicantName: "John Doe",
    status: "Registered",
    class: 5,
    companyId: "vtm",
    renewedUptoDate: "",
    goods:
      "Hello world Hello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello worldHello world"
  },
  {
    fileNo: "123456",
    tradeMarkId: 3453453,
    name: "Barbrick",
    applicationDate: "24-02-2020",
    applicantName: "dfsdfsdf",
    status: "Accepted",
    class: 30,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "sf sdf sdf"
  },
  {
    fileNo: "5656",
    tradeMarkId: 7653421,
    name: "Test mark12",
    applicationDate: "",
    applicantName: "ABC company",
    status: "Accepted",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "5555",
    tradeMarkId: 7654321,
    name: "Barbrick12",
    applicationDate: "",
    applicantName: "Test Name",
    status: "Showcause Hearing",
    class: 5,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "3434",
    tradeMarkId: 343434,
    name: "ffss",
    applicationDate: "24-02-2020",
    applicantName: "ZMCL",
    status: "New Application",
    class: 5,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "1234",
    tradeMarkId: 12341234,
    name: "tysma",
    applicationDate: "",
    applicantName: "Siddharth Vidhani",
    status: "Registered",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "3445",
    tradeMarkId: 456545,
    name: "dkks",
    applicationDate: "",
    applicantName: "NA",
    status: "Registered",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "10-06-2020",
    goods: "NA"
  },
  {
    fileNo: "22334",
    tradeMarkId: 3444445,
    name: "ssnd",
    applicationDate: "13-05-2020",
    applicantName: "NA",
    status: "Accepted",
    class: 2,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "1245",
    tradeMarkId: 12344443,
    name: "diset",
    applicationDate: "",
    applicantName: "NA",
    status: "Accepted",
    class: 5,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "123456",
    tradeMarkId: 3456644,
    name: "vggg",
    applicationDate: "",
    applicantName: "NA",
    status: "Accepted",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "1245678",
    tradeMarkId: 1245678,
    name: "1245678",
    applicationDate: "",
    applicantName: "NA",
    status: "Registered",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "12335",
    tradeMarkId: 3456789,
    name: "dfsdfsdf",
    applicationDate: "24-02-2020",
    applicantName: "sadasdas",
    status: "Accepted",
    class: 2,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "2222",
    tradeMarkId: 222222,
    name: "2222",
    applicationDate: "14-03-2020",
    applicantName: "2222",
    status: "Accepted",
    class: 21,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "222233"
  },
  {
    fileNo: "123456",
    tradeMarkId: 123456,
    name: "123456",
    applicationDate: "",
    applicantName: "NA",
    status: "Registered",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "123456",
    tradeMarkId: 345354353454,
    name: "Barbrick",
    applicationDate: "24-02-2020",
    applicantName: "dfdsfsfs",
    status: "Accepted",
    class: 4,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "23433",
    tradeMarkId: 334567,
    name: "fdsse",
    applicationDate: "",
    applicantName: "NA",
    status: "Accepted",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "3322",
    tradeMarkId: 332222,
    name: "ffsasa",
    applicationDate: "",
    applicantName: "NA",
    status: "Accepted",
    class: 0,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "1235",
    tradeMarkId: 234556,
    name: "gddd",
    applicationDate: "22-05-2020",
    applicantName: "NA",
    status: "Accepted",
    class: 40,
    companyId: "vtm",
    renewedUptoDate: "",
    goods: "NA"
  },
  {
    fileNo: "123456",
    tradeMarkId: 28,
    name: "HELLO",
    applicationDate: "22-02-2020",
    applicantName: "SOMETHING",
    status: "Showcause Hearing",
    class: 45,
    companyId: "vtm",
    renewedUptoDate: "22-02-2020",
    goods: "scascsac"
  }
];
export default tabledata;
