export default {
  services: [
    {
      firstName: "Venkatasubramanian",
      lastName: "Jayaraman",
      gender: "male",
      mobileNumber: "+15146511501",
      experience: "6",
      professionalid: "d7487016-0282-4a12-b3ca-15bdbd308439",
      description:
        "I'm an experienced Handyman and will definitely do a good job .",
      primarySkill: "Carpenter",
      secondarySkill: "Dry wall installation",
      payPerhr: "25",
      profAddr: "502-1160 rue saint mathieu",
      email: "jvsmn65@gmail.com",
      cognitoId: "0a197b30-5b91-4fce-b4e1-caef18ff1d80",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Joey",
      lastName: "Tribbiani",
      gender: "male",
      mobileNumber: "+15143336578",
      experience: "10",
      professionalid: "f5368d3e-eb16-40df-8dc5-292dddea3baa",
      description:
        "I'm highly experienced in any plumbing related issues. I'm pretty sure I will be able to get the job done. Please book an appointment for the job.",
      primarySkill: "Plumber",
      secondarySkill: "Electrician",
      payPerhr: "30",
      profAddr: "Central Perk",
      email: "srikrishnan.venkatasubramanian@gmail.com",
      cognitoId: "629aaad9-8527-4ec9-9f35-98b41a942c38",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Srikrishnan",
      lastName: "Venkatasubramanian",
      gender: "male",
      mobileNumber: "+15146511501",
      experience: "4",
      professionalid: "4986a9fe-339e-49f3-827a-0f2e3742df5e",
      description:
        "I'm a very experienced technician and can do works related to fixing laptops, TV's and any other electronics. I'm also an experienced mechanic. Please book an appointment for the job.",
      primarySkill: "Technician",
      secondarySkill: "Mechanic",
      payPerhr: "20",
      profAddr: "241A Cedarbrae Ave",
      email: "sreemayiladu@gmail.com",
      cognitoId: "a563d296-dbb5-419a-834f-1d320bbd42ab",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Meghana",
      lastName: "Nagaraj",
      gender: "female",
      mobileNumber: "+15483332977",
      experience: "3",
      professionalid: "19bcdb7a-9cec-43b5-b4e3-afef0bae9337",
      description: "Please book an appointment.",
      primarySkill: "Stylist",
      secondarySkill: "HomeDecor",
      payPerhr: "25",
      profAddr: "241A\nCedarbrae Ave",
      email: "meghananagaraj94@gmail.com",
      cognitoId: "d5d7ed5c-e7d8-4da8-9435-be08f468e6e6",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Francoise",
      lastName: "Rautenstrauch",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Plumber",
      secondarySkill: "Snow shovelling",
      payPerhr: "$100",
      profAddr: "abc",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Kendra",
      lastName: "Loud",
      gender: "male",
      mobilenumber: 123456789,
      experience: 10,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Carpenter",
      secondarySkill: "Technician",
      payPerhr: "$150",
      profAddr: "def",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Lourdes",
      lastName: "Bauswell",
      gender: "other",
      mobilenumber: 123456789,
      experience: 1,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Homedecor",
      secondarySkill: "Mechanic",
      payPerhr: "$200",
      profAddr: "hij",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Hannah",
      lastName: "Edmison",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 3,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Stylist",
      secondarySkill: "Drywall Installation",
      payPerhr: "$50",
      profAddr: "lmn",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Tom",
      lastName: "Loeza",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Electrician",
      secondarySkill: "Fixture Replacement ",
      payPerhr: "$174",
      profAddr: "opq",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Queenie",
      lastName: "Kramarczyk",
      gender: "other",
      mobilenumber: 123456789,
      experience: 6,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Maintainence",
      secondarySkill: "Power Washing",
      payPerhr: "$90",
      profAddr: "rst",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Hui",
      lastName: "Portaro",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 2,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Refrigirataion",
      secondarySkill: "Window repair ",
      payPerhr: "$80",
      profAddr: "uvw",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Josefa",
      lastName: "Opitz",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Snow shovelling",
      secondarySkill: "small appliance repair ",
      payPerhr: "$500",
      profAddr: "xyz",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Lea",
      lastName: "Steinhaus",
      gender: "other",
      mobilenumber: 123456789,
      experience: 7,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Technician",
      secondarySkill: "Tile installation ",
      payPerhr: "$60",
      profAddr: "abc",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Paola",
      lastName: "Vielma",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 8,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Mechanic",
      secondarySkill: "Security system",
      payPerhr: "$70",
      profAddr: "def",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Hortencia",
      lastName: "Bresser",
      gender: "male",
      mobilenumber: 123456789,
      experience: 9,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Drywall Installation",
      secondarySkill: "Plumber",
      payPerhr: "$79",
      profAddr: "hij",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Leanna",
      lastName: "Tijerina",
      gender: "other",
      mobilenumber: 123456789,
      experience: 1,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Fixture Replacement ",
      secondarySkill: "Carpenter",
      payPerhr: "$100",
      profAddr: "lmn",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Danilo",
      lastName: "Pride",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Power Washing",
      secondarySkill: "Homedecor",
      payPerhr: "$150",
      profAddr: "opq",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Huey",
      lastName: "Marcille",
      gender: "male",
      mobilenumber: 123456789,
      experience: 10,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Window repair ",
      secondarySkill: "Stylist",
      payPerhr: "$200",
      profAddr: "rst",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Apolonia",
      lastName: "Warne",
      gender: "other",
      mobilenumber: 123456789,
      experience: 1,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "small appliance repair ",
      secondarySkill: "Electrician",
      payPerhr: "$50",
      profAddr: "uvw",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Chandra",
      lastName: "Lagos",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 3,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Tile installation ",
      secondarySkill: "Snow shovelling",
      payPerhr: "$174",
      profAddr: "xyz",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Crissy",
      lastName: "Pacholec",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Security system",
      secondarySkill: "Technician",
      payPerhr: "$90",
      profAddr: "abc",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Gianna",
      lastName: "Branin",
      gender: "other",
      mobilenumber: 123456789,
      experience: 6,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Plumber",
      secondarySkill: "Mechanic",
      payPerhr: "$80",
      profAddr: "def",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Valentin",
      lastName: "Billa",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 2,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Carpenter",
      secondarySkill: "Drywall Installation",
      payPerhr: "$500",
      profAddr: "hij",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Ilona",
      lastName: "Dudash",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Homedecor",
      secondarySkill: "Fixture Replacement ",
      payPerhr: "$60",
      profAddr: "lmn",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Willard",
      lastName: "Lablanc",
      gender: "other",
      mobilenumber: 123456789,
      experience: 7,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Stylist",
      secondarySkill: "Power Washing",
      payPerhr: "$70",
      profAddr: "opq",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Lauryn",
      lastName: "Randol",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 8,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Electrician",
      secondarySkill: "Window repair ",
      payPerhr: "$79",
      profAddr: "rst",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Laurena",
      lastName: "Begin",
      gender: "male",
      mobilenumber: 123456789,
      experience: 9,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Maintainence",
      secondarySkill: "small appliance repair ",
      payPerhr: "$100",
      profAddr: "uvw",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Elise",
      lastName: "Michelle",
      gender: "other",
      mobilenumber: 123456789,
      experience: 1,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Refrigirataion",
      secondarySkill: "Tile installation ",
      payPerhr: "$150",
      profAddr: "xyz",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Corrie",
      lastName: "Kardell",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Snow shovelling",
      secondarySkill: "Security system",
      payPerhr: "$200",
      profAddr: "abc",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Kimberely",
      lastName: "Rabuse",
      gender: "male",
      mobilenumber: 123456789,
      experience: 10,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Technician",
      secondarySkill: "Plumber",
      payPerhr: "$50",
      profAddr: "def",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Tish",
      lastName: "Violett",
      gender: "other",
      mobilenumber: 123456789,
      experience: 1,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Mechanic",
      secondarySkill: "Carpenter",
      payPerhr: "$174",
      profAddr: "hij",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Hollis",
      lastName: "Stanfield",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 3,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Drywall Installation",
      secondarySkill: "Homedecor",
      payPerhr: "$90",
      profAddr: "lmn",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Andree",
      lastName: "Christmann",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Fixture Replacement ",
      secondarySkill: "Stylist",
      payPerhr: "$80",
      profAddr: "opq",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Lyla",
      lastName: "Fucillo",
      gender: "other",
      mobilenumber: 123456789,
      experience: 6,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Power Washing",
      secondarySkill: "Electrician",
      payPerhr: "$500",
      profAddr: "rst",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Felton",
      lastName: "Yafuso",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 2,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Window repair ",
      secondarySkill: "Snow shovelling",
      payPerhr: "$60",
      profAddr: "uvw",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Dell",
      lastName: "Polino",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "small appliance repair ",
      secondarySkill: "Technician",
      payPerhr: "$70",
      profAddr: "xyz",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Nohemi",
      lastName: "Leko",
      gender: "other",
      mobilenumber: 123456789,
      experience: 7,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Tile installation ",
      secondarySkill: "Mechanic",
      payPerhr: "$79",
      profAddr: "abc",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Tambra",
      lastName: "Lembke",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 8,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Security system",
      secondarySkill: "Drywall Installation",
      payPerhr: "$100",
      profAddr: "def",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Vicki",
      lastName: "Maikoksoong",
      gender: "male",
      mobilenumber: 123456789,
      experience: 9,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Plumber",
      secondarySkill: "Fixture Replacement ",
      payPerhr: "$150",
      profAddr: "hij",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Renato",
      lastName: "Airhart",
      gender: "other",
      mobilenumber: 123456789,
      experience: 1,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Carpenter",
      secondarySkill: "Power Washing",
      payPerhr: "$200",
      profAddr: "lmn",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Lenita",
      lastName: "Darbro",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Homedecor",
      secondarySkill: "Window repair ",
      payPerhr: "$50",
      profAddr: "opq",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Barney",
      lastName: "Hagen",
      gender: "male",
      mobilenumber: 123456789,
      experience: 10,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Stylist",
      secondarySkill: "small appliance repair ",
      payPerhr: "$174",
      profAddr: "rst",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Matthew",
      lastName: "Armacost",
      gender: "other",
      mobilenumber: 123456789,
      experience: 1,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Electrician",
      secondarySkill: "Tile installation ",
      payPerhr: "$90",
      profAddr: "uvw",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Belen",
      lastName: "Nelton",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 3,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Maintainence",
      secondarySkill: "Security system",
      payPerhr: "$80",
      profAddr: "xyz",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Iesha",
      lastName: "Wardle",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Refrigirataion",
      secondarySkill: "Plumber",
      payPerhr: "$500",
      profAddr: "abc",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Francesco",
      lastName: "Sarchet",
      gender: "other",
      mobilenumber: 123456789,
      experience: 6,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Snow shovelling",
      secondarySkill: "Carpenter",
      payPerhr: "$60",
      profAddr: "def",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Paulene",
      lastName: "Rhule",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 2,
      professionalid: "455621655ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Technician",
      secondarySkill: "Homedecor",
      payPerhr: "$70",
      profAddr: "hij",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Carole",
      lastName: "Hughlett",
      gender: "male",
      mobilenumber: 123456789,
      experience: 5,
      professionalid: "56523256ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Mechanic",
      secondarySkill: "Stylist",
      payPerhr: "$79",
      profAddr: "lmn",
      email: "hhz@hotmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Miss",
      lastName: "Dunning",
      gender: "other",
      mobilenumber: 123456789,
      experience: 7,
      professionalid: "7f0475ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Drywall Installation",
      secondarySkill: "Electrician",
      payPerhr: "$100",
      profAddr: "opq",
      email: "herz@yahoo.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
    {
      firstName: "Elfrieda",
      lastName: "Hinsch",
      gender: "Female",
      mobilenumber: 123456789,
      experience: 8,
      professionalid: "54652165ed-3941-4de3-80e6-a51f0ff5b77d",
      description: "To be decided",
      primarySkill: "Fixture Replacement ",
      secondarySkill: "Snow shovelling",
      payPerhr: "$150",
      profAddr: "rst",
      email: "xyz@gmail.com",
      cognitoId: "Test",
      image:
        "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    },
  ],
};
