/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const AWS_CONFIG = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:977c072c-34de-410d-9d2f-d960c7e0ae1e",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_sJVkAAwO6",
  aws_user_pools_web_client_id: "4ekdlng8vs32f3fo5lgjbhi4jn",
  oauth: {},
};

export default AWS_CONFIG;
